### ISSUE TITLE
IPv6 support is not working

### ISSUE THREAD

**Issue by ptnapoleon** [pcmanus/ccm#185]
Cannot start a node as '::1', which is ipv6 localhost.

**Comment by aholmberg** [comment]
I also noticed this. It seems like C* will no longer start with ipv6, even if the appropriate defines are present.

**Comment by kishkaru** [comment]
I'm able to start with an ipformat="::1", enabling ipv6 on CCM. However, I can't bind more than one node/loopback. For example, using two addresses (passing a list of `[1, 2]` as nodes to `Cluster.populate()` causes `Cluster.start()` to raise:
```
  File "ccmlib/cluster.py", line 249, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options)
  File "ccmlib/node.py", line 443, in start
    common.check_socket_available(itf)
  File "ccmlib/common.py", line 341, in check_socket_available
    raise UnavailableSocketError("Inet address %s:%s is not available: %s" % (addr, port, msg))

UnavailableSocketError: Inet address 0:0:0:0:0:0:0:2:9042 is not available: [Errno 99] Cannot assign requested address
```

**Comment by mshuler** [comment]
I've tried quite a few different variations of passing in --ip-format= without success. The basic issue of IPv6 loopback only containing a single address, without the ability to utilize additional loopback addresses is by design [0] and a draft update to that design has been proposed, but not accepted [1].

I've added the proposed loopback route, configured a few addresses, they seem to work, but ccm fails to parse my option.

```
mshuler@hana:~$ sudo ip -6 route add ::1/48 dev lo   
mshuler@hana:~$ sudo ip -6 addr add ::2/128 dev lo 
mshuler@hana:~$ sudo ip -6 addr add ::3/128 dev lo 
mshuler@hana:~$ sudo ip -6 addr add ::4/128 dev lo 
mshuler@hana:~$ route -6 | grep lo
::1/128                        ::                         U    256 0     0 lo
::2/128                        ::                         !n   256 0     0 lo
::3/128                        ::                         !n   256 0     0 lo
::4/128                        ::                         !n   256 0     0 lo
::/48                          ::                         !n   1024 0     0 lo
::/0                           ::                         !n   -1  11257292 lo
::1/128                        ::                         Un   0   3  1811 lo
::2/128                        ::                         Un   0   1     0 lo
::3/128                        ::                         Un   0   1     0 lo
::4/128                        ::                         Un   0   1     0 lo
fe80::800:27ff:fe00:0/128      ::                         Un   0   1     0 lo
fe80::3e97:eff:fe8c:27b6/128   ::                         Un   0   1     0 lo
::/0                           ::                         !n   -1  11257292 lo
mshuler@hana:~$ ping6 -c3 ::1
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from ::1: icmp_seq=2 ttl=64 time=0.046 ms
64 bytes from ::1: icmp_seq=3 ttl=64 time=0.054 ms

--- ::1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.041/0.047/0.054/0.005 ms
mshuler@hana:~$ ping6 -c3 ::2
PING ::2(::2) 56 data bytes
64 bytes from ::2: icmp_seq=1 ttl=64 time=0.046 ms
64 bytes from ::2: icmp_seq=2 ttl=64 time=0.046 ms
64 bytes from ::2: icmp_seq=3 ttl=64 time=0.051 ms

--- ::2 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.046/0.047/0.051/0.008 ms
mshuler@hana:~$ ping6 -c3 ::3
PING ::3(::3) 56 data bytes
64 bytes from ::3: icmp_seq=1 ttl=64 time=0.050 ms
64 bytes from ::3: icmp_seq=2 ttl=64 time=0.040 ms
64 bytes from ::3: icmp_seq=3 ttl=64 time=0.060 ms

--- ::3 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.040/0.050/0.060/0.008 ms
mshuler@hana:~$ ping6 -c3 ::4
PING ::4(::4) 56 data bytes
64 bytes from ::4: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from ::4: icmp_seq=2 ttl=64 time=0.049 ms
64 bytes from ::4: icmp_seq=3 ttl=64 time=0.057 ms

--- ::4 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.049/0.051/0.057/0.009 ms
mshuler@hana:~$ ccm status
No currently active cluster (use ccm cluster switch)
mshuler@hana:~$ ccm create v6test -v binary:2.0.15 -n 3 -s -d --ip-format="::1"
Downloading http://archive.apache.org/dist/cassandra/2.0.15/apache-cassandra-2.0.15-bin.tar.gz to /tmp/ccm-IaS0m8.tar.gz (17.273MB)
  18111795  [100.00%]
Extracting /tmp/ccm-IaS0m8.tar.gz as version 2.0.15 ...
Current cluster is now: v6test
Traceback (most recent call last):
  File "/home/mshuler/git/ccm/ccm", line 72, in <module>
    cmd.run()
  File "/home/mshuler/git/ccm/ccmlib/cmds/cluster_cmds.py", line 166, in run
    cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
  File "/home/mshuler/git/ccm/ccmlib/cluster.py", line 158, in populate
    binary = (ipformat % i, 9042)
TypeError: not all arguments converted during string formatting
mshuler@hana:~$
```

[0] https://tools.ietf.org/html/rfc4291#section-2.5.3
[1] https://tools.ietf.org/html/draft-smith-v6ops-larger-ipv6-loopback-prefix-00

**Comment by kishkaru** [comment]
Update: a 1 node ipv6 does work by using ` ipformat='::%d'`

**Comment by mshuler** [comment]
Armed with that info (thanks!), this partially works:
```
mshuler@hana:~$ sudo ip -6 route add ::1/48 dev lo   
mshuler@hana:~$ sudo ip -6 addr add ::2/128 dev lo 
mshuler@hana:~$ sudo ip -6 addr add ::3/128 dev lo 
mshuler@hana:~$ sudo ip -6 addr add ::4/128 dev lo
mshuler@hana:~$ ccm status
Cluster: 'v6test'
-----------------
node1: UP
node3: UP
node2: UP
mshuler@hana:~$ ccm node1 status
Traceback (most recent call last):
  File "/home/mshuler/git/ccm/ccm", line 72, in <module>
    cmd.run()
  File "/home/mshuler/git/ccm/ccmlib/cmds/node_cmds.py", line 228, in run
    stdout, stderr = self.node.nodetool(self.nodetool_cmd + " " + " ".join((self.args[1:])))
  File "/home/mshuler/git/ccm/ccmlib/node.py", line 595, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/home/mshuler/.ccm/repository/2.1.6/bin/nodetool -h localhost -p 7100 status' failed; exit status: 1; stderr: nodetool: Failed to connect to 'localhost:7100' - ConnectException: 'Connection refused'.

mshuler@hana:~$ nodetool -h ::1 -p 7100 status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns (effective)  Host ID                               Rack
UN  0:0:0:0:0:0:0:1  46.43 KB   1       66.7%             3cdac2e3-a512-4bd9-8133-0a1f50141e1c  rack1
UN  0:0:0:0:0:0:0:2  46.51 KB   1       66.7%             c280b410-bcb2-4f36-bbc9-96fa12b492f2  rack1
UN  0:0:0:0:0:0:0:3  46.43 KB   1       66.7%             91700b70-8954-4f61-a925-aa0cc1a4566b  rack1
```

"localhost" on my machine resolves to 127.0.0.1 and ::1, so the connection was refused since the v4 address was selected first, without retrying. On other people's machines, v6 may be tried first, or "localhost" may not have a v6 entry in /etc/hosts at all, but may contain a ip6-localhost entry. An IRC discussion resulted in perhaps ccm should be using the specified node IP address (v4 or v6) as configured for the cluster, instead of assuming "localhost" might do the right thing.

**Comment by mshuler** [comment]
Patch psuedo suggestion:
- remove usage of "localhost" everywhere
- if --ip-format is not passed in as an option, default to using "127.0.0.%d" for nodetool and all other utils
- if --ip-format is passed in as an option, use the defined format (ie. "::%d") for nodetool and all other utils

**Comment by clintascencio** [comment]
I've had intermittent success with using a multinode IPv6 cluster for OS X with [a commit I made on my fork(https://github.com/clintascencio/ccm/commit/dc8089517dd00614dae934644d608d3c8c0fc35b)

I've had intermittent success because the cluster sometimes starts in IPv6 and sometimes gives me a java.net.SocketException: Protocol family unavailable. Even if the SocketException occurs for a cluster, you can start it in IPv6 by restarting it until it works.

The SocketException occurs because -Djava.net.preferIPv4Stack is set to true, but that shouldn't be the case with the changes I've made and I haven't been able to figure out what's causing Cassandra to start in IPv4 instead of IPv6.

About my commit:
At least for OS X, -Djava.net.preferIPv6Addresses=true causes Cassandra to fail, so instead -Djava.net.preferIPv4Stack=true is commented out. The option also moves inbetween versions, cassandra-env.sh < 3.2 and jvm.options >= 3.2.

Command I use:
./ccm create test -v 3.1 -n 3 -d -s --ip-format="::%d"

The loopbacks I use:
sudo ifconfig lo0 inet6 alias 0:0:0:0:0:0:0:1
sudo ifconfig lo0 inet6 alias 0:0:0:0:0:0:0:2
sudo ifconfig lo0 inet6 alias 0:0:0:0:0:0:0:3

**Comment by ptnapoleon** [comment]
Any idea how well that change works on linux?

**Comment by clintascencio** [comment]
In the jvm.options/cassandra-env.sh, they recommend commenting out the IPv4 jvm argument (Instead of changing to the argument to -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true) to start it in IPv6, so it should work in linux as it does in OS X.

**Comment by ptnapoleon** [comment]
Well I'm willing to merge it in then, if you make a PR
