### ISSUE TITLE
Support for 2.1.1

### ISSUE THREAD

**Issue by 0x6e6562** [pcmanus/ccm#195]
I was wondering whether ccm supports 2.1.1 yet - I'm getting the following issue:

```
+ccm create test -v binary:2.1.1 -n 3 -d --vnodes
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==1.2', 'ccm')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 517, in run_script
    """Add `dist` to working set, associated with `entry`
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1430, in run_script
    return real_path
  File "/usr/local/lib/python2.7/dist-packages/ccm-1.2-py2.7.egg/EGG-INFO/scripts/ccm", line 72, in <module>
    
  File "build/bdist.linux-x86_64/egg/ccmlib/cmds/cluster_cmds.py", line 99, in run
  File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 43, in __init__
  File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 38, in setup
  File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 151, in download_version
ccmlib.common.ArgumentError: Invalid version 2.1.1 (underlying error is: HTTP Error 404: Not Found)
```

**Comment by Zariel** [comment]
Hi @ptnapoleon im seeing this again, seeing at least 1 404 failure per test run on differing versions, the versions all seem to be in the apache archive, this was from 2.2.3

`
test does not appear to be a valid cluster (use ccm list to view valid clusters)
Traceback (most recent call last):
  File "/home/travis/.local/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.1.2', 'ccm')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 696, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1621, in run_script
  File "/home/travis/.local/lib/python2.7/site-packages/ccm-2.1.2-py2.7.egg/EGG-INFO/scripts/ccm", line 74, in <module>
    
  File "build/bdist.linux-x86_64/egg/ccmlib/cmds/cluster_cmds.py", line 150, in run
  File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 59, in __init__
  File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 72, in load_from_repository
  File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 80, in setup
ccmlib.common.ArgumentError: Invalid version 2.2.3 (underlying error is: HTTP Error 404: Not Found)
`

**Comment by ptnapoleon** [comment]
@Zariel Can I see the command you are using to create the cluster? We added automatic retry, as this 404 started becoming a common problem.

**Comment by Zariel** [comment]
We run, `ccm create test -v binary:$version -n $clusterSize -d --vnodes --jvm_arg="-Xmx256m -XX:NewSize=100m"`

where clusterSize is 3, and version is one of 2.0.17, 2.1.11, 2.2.3

**Comment by ptnapoleon** [comment]
Okay. So the good news is I know what's going on, but the bad news is I may not be 100% able to help.

You should no longer need to specify `binary:`, as that is now the default option when you choose a version. Second, if you aren't explicitly specifying `binary`, then if that 404s, CCM will automatically fall back to building from source. However, if you absolutely need to install from the binaries, as building from source in untenable for whatever reason, then there isn't much I can suggest here. 

The root issue is that sometimes the archive.apache.org load balancer redirects to a bad mirror. What we'll see is that for a given version line, the newest version will sometimes not exist on a given mirror. The failure will exist transiently for a minute or so. Repeated retries weren't helping, thus why we fall back to building from source.

If building from source is a no-no, then you could fall back to trying an earlier version in your test code? So if 2.0.17 fails, fall back to 2.0.16? You could also try hosting the binaries yourself somewhere, and redirect CCM to use that URL, instead of the apache archive site.

**Comment by Zariel** [comment]
We can compile the binary ourselves, travis allows us to cache it so it should only get built rarely.
