### ISSUE TITLE
dse url

### ISSUE THREAD

**Issue by ikaz** [pcmanus/ccm#251]
I'm trying to create a dse cluster but I keep getting an invalid url error. I manually downloaded dse (mac) from the webpage so I had to register and I got a username and password. I'm using this username/password combination to create a cluster as below. I keep getting the same error with and without sudo.

./ccm create --dse --dse-username=my_usernaname  --dse-password=my_password test -v 2.0.5 -n 3 -s

Traceback (most recent call last):
  File "./ccm", line 72, in <module>
    cmd.run()
  File "/Users/icaste/gitext/ccm/ccmlib/cmds/cluster_cmds.py", line 124, in run
    cluster = DseCluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, dse_username=self.options.dse_username, dse_password=self.options.dse_password, opscenter=self.options.opscenter, verbose=True)
  File "/Users/icaste/gitext/ccm/ccmlib/dse_cluster.py", line 18, in __init__
    super(DseCluster, self).__init__(path, name, partitioner, install_dir, create_directory, version, verbose)
  File "/Users/icaste/gitext/ccm/ccmlib/cluster.py", line 51, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/Users/icaste/gitext/ccm/ccmlib/dse_cluster.py", line 25, in load_from_repository
    return repository.setup_dse(version, self.dse_username, self.dse_password, verbose)
  File "/Users/icaste/gitext/ccm/ccmlib/repository.py", line 47, in setup_dse
    download_dse_version(version, username, password, verbose=verbose)
  File "/Users/icaste/gitext/ccm/ccmlib/repository.py", line 150, in download_dse_version
    raise ArgumentError(msg)
ccmlib.common.ArgumentError: Invalid url http://downloads.datastax.com/enterprise/dse-2.0.5-bin.tar.gz (underlying error is: HTTP Error 404: Not Found)

Am I'm missing anything? Thanks!

**Comment by ptnapoleon** [comment]
Is 2.0.5 a valid version of DSE?

**Comment by ikaz** [comment]
Not 100% sure if it is but I tried with a valid version (4.6.0) and the download succeeded. Thanks!

**Comment by ptnapoleon** [comment]
I have checked, and it is not a version. Good to hear 4.6.0 worked for you.
