### ISSUE TITLE
maven-ant-tasks-download failing with java.io.IOException

### ISSUE THREAD

**Issue by advaitvdeo** [pcmanus/ccm#268]
I am getting following error with ccm create command

```
ccm create --version=2.0.9 --nodes=6 deo
Downloading http://archive.apache.org/dist/cassandra/2.0.9/apache-cassandra-2.0.9-src.tar.gz to /tmp/ccm-2oKzAH.tar.gz (10.810MB)
  11335077  [100.00%]
Extracting /tmp/ccm-2oKzAH.tar.gz as version 2.0.9 ...
Compiling Cassandra 2.0.9 ...
Deleted /home/local/ANT/advaitd/.ccm/repository/2.0.9 due to error
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 5, in <module>
    pkg_resources.run_script('ccm==2.0.3.1', 'ccm')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/EGG-INFO/scripts/ccm", line 72, in <module>
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/ccmlib/cmds/cluster_cmds.py", line 127, in run
    cluster = Cluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/ccmlib/cluster.py", line 51, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/ccmlib/cluster.py", line 64, in load_from_repository
    return repository.setup(version, verbose)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/ccmlib/repository.py", line 40, in setup
    download_version(version, verbose=verbose, binary=binary)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.3.1-py2.7.egg/ccmlib/repository.py", line 221, in download_version
    raise e
ccmlib.common.CCMError: Error compiling Cassandra. See /home/local/ANT/advaitd/.ccm/repository/last.log for details
```

last.log shows following
```
Buildfile: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build.xml

init:
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/classes/main
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/classes/thrift
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/test/lib
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/test/classes
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/src/gen-java
    [mkdir] Created dir: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/lib

maven-ant-tasks-localrepo:

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/maven-ant-tasks-2.1.3.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] Error opening connection java.io.IOException: Server returned HTTP response code: 403 for URL: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] Can't get http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar to /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/maven-ant-tasks-2.1.3.jar

BUILD FAILED
/home/local/ANT/advaitd/.ccm/repository/2.0.9/build.xml:275: Can't get http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar to /home/local/ANT/advaitd/.ccm/repository/2.0.9/build/maven-ant-tasks-2.1.3.jar

Total time: 1 second
```

Could you please suggest what is wrong with my environment

Following are settings in my environment

```
advaitd@desktop:~$ python -V 
Python 2.7.3

advaitd@desktop:~$ ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011

advaitd@desktop:~$ mvn -version
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-44-generic", arch: "amd64", family: "unix"

advaitd@desktop:~$ java -version
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

```

**Comment by ptnapoleon** [comment]
There doesn't appear to be anything wrong with your environment. The HTTP 403 error implies there is some sort of connection issue to maven central. Are you able to install any other version from source? If you run `ccm invalidatecache` and try again, does it work? You can install with `-v binary:2.0.9` instead of `'v 2.0.9` to use the already compiled release as a workaround.

**Comment by advaitvdeo** [comment]
Tried ccm invalidate and after that tried ccm create. Still getting same error

But when I tried -v binary:2.0.9, it worked :)

Thanks a lot for your help !!
