### ISSUE TITLE
FileNotFoundException when Starting DSE Cluster

### ISSUE THREAD

**Issue by mniehoff** [pcmanus/ccm#269]
Hi,

I have the following Cluster:

ccm create --dse -v 4.6.5 --dse-username=name --dse-password=password -o 5.1.1 -n 3 music

When starting the cluster with ccm start I get this message for each node:

```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /var/log/cassandra/solrvalidation.log (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:395)
	at org.apache.log4j.PropertyWatchdog.doOnChange(PropertyConfigurator.java:955)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:89)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:58)
	at org.apache.log4j.PropertyWatchdog.<init>(PropertyConfigurator.java:947)
	at org.apache.log4j.PropertyConfigurator.configureAndWatch(PropertyConfigurator.java:473)
	at org.apache.cassandra.service.CassandraDaemon.initLog4j(CassandraDaemon.java:140)
	at org.apache.cassandra.service.CassandraDaemon.<clinit>(CassandraDaemon.java:88)
```

Using version 2.0.3, installed with homebrew.

Cheers.

**Comment by ptnapoleon** [comment]
We have changes to solr in ccm that may fix your issue. They are currently unreleased. I can cut a release tomorrow that will include them? Or you can install ccm from source on github and see if it fixes your problem.
