### ISSUE TITLE
CCM Fails when powershell not on path in Windows

### ISSUE THREAD

**Issue by williamconti** [pcmanus/ccm#322]
I am having a big issue with ccm on windows, i try to launch it but it gives me this error message:

Current cluster is now: test
Traceback (most recent call last):
  File "C:\Python27\Scripts\ccm.py", line 72, in <module>
    cmd.run()
  File "C:\Python27\lib\site-packages\ccmlib\cmds\cluster_cmds.py", line 173, in run
    if cluster.start(verbose=self.options.debug_log, wait_for_binary_proto=self.options.binary_protocol, jvm_args=self.options.jvm_args, profile_options=pro
file_options) is None:
  File "C:\Python27\lib\site-packages\ccmlib\cluster.py", line 249, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options)
  File "C:\Python27\lib\site-packages\ccmlib\node.py", line 439, in start
    if common.is_win() and not common.is_ps_unrestricted() and self.cluster.version() >= '2.1':
  File "C:\Python27\lib\site-packages\ccmlib\common.py", line 210, in is_ps_unrestricted
    p = subprocess.Popen(['powershell', 'Get-ExecutionPolicy'], stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 672, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 882, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

I followed all the steps from datastax blog: http://www.datastax.com/dev/blog/ccm-2-0-and-windows But unfortunately, nothing works.

Any idea?

**Comment by ptnapoleon** [comment]
If you run `Get-ExecutionPolicy` in powershell yourself, what is returned?

**Comment by williamconti** [comment]
It says "Unrestricted"

**Comment by williamconti** [comment]
Solved! I just needed to add Powershell to the windows path

**Comment by ptnapoleon** [comment]
Thanks! I was not aware Windows would ever have powershell not on the path by default. That would definitely break ccm. I'll leave this open for handling this issue better.
