### ISSUE TITLE
create -v git:whatever is broken

### ISSUE THREAD

**Issue by EnigmaCurry** [pcmanus/ccm#334]
Trying by removing my entire ~/.ccm directory, and instantiating a 2.2 cluster fails:

```
12:12 PM:~/git/datastax/ccm[master*]$ rm -rf ~/.ccm
12:12 PM:~/git/datastax/ccm[master*]$ git pull
Already up-to-date.
12:12 PM:~/git/datastax/ccm[master*]$ ccm create -v git:cassandra-2.2 -n 1 -s test
http://git-wip-us.apache.org/repos/asf/cassandra.git git:cassandra-2.2
Cloning Cassandra...
Cloning Cassandra (from local cache)
Checking out requested branch (cassandra-2.2)
Compiling Cassandra cassandra-2.2 ...
Current cluster is now: test
[node1 ERROR] Invalid yaml. Please remove properties [tracetype_query_ttl, roles_validity_in_ms, enable_user_defined_functions, windows_timer_interval, role_manager, batch_size_fail_threshold_in_kb, tracetype_repair_ttl] from your cassandra.yaml
Fatal configuration error; unable to start. See log for stacktrace.
Traceback (most recent call last):
  File "/usr/bin/ccm", line 8, in <module>
    execfile(__file__)
  File "/home/ryan/git/datastax/ccm/ccm", line 72, in <module>
    cmd.run()
  File "/home/ryan/git/datastax/ccm/ccmlib/cmds/cluster_cmds.py", line 174, in run
    if cluster.start(verbose=self.options.debug_log, wait_for_binary_proto=self.options.binary_protocol, jvm_args=self.options.jvm_args, profile_options=profile_options) is None:
  File "/home/ryan/git/datastax/ccm/ccmlib/cluster.py", line 277, in start
    raise NodeError("Error starting {0}.".format(node.name), p)
ccmlib.node.NodeError: Error starting node1.
```

The error varies, but this is the most recent form I've seen.

**Comment by EnigmaCurry** [comment]
works now :(
