### ISSUE TITLE
Warn when wrong JDK is used for C* 3.0

### ISSUE THREAD

**Issue by kishkaru** [pcmanus/ccm#347]
Currently it just outputs a stacktrace:

```
Compiling Cassandra 3.0.0-alpha1 ...
Deleted /home/kishan/.ccm/repository/3.0.0-alpha1 due to error
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 5, in <module>
    pkg_resources.run_script('ccm==2.0.4.1', 'ccm')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ccm-2.0.4.1-py2.7.egg/EGG-INFO/scripts/ccm", line 72, in <module>
    
  File "build/bdist.linux-x86_64/egg/ccmlib/cmds/cluster_cmds.py", line 130, in run
  File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 56, in __init__
  File "build/bdist.linux-x86_64/egg/ccmlib/cluster.py", line 69, in load_from_repository
  File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 44, in setup
  File "build/bdist.linux-x86_64/egg/ccmlib/repository.py", line 231, in download_version
ccmlib.common.CCMError: Error compiling Cassandra. See /home/kishan/.ccm/repository/last.log for details
```

A nicer error output would be nice. 
Also it would be nice to check the version of the default JDK before trying to compile or even download the tar, so we don't waste time.

**Comment by kishkaru** [comment]
The default JDK or JAVA_HOME, since that environment var may also be set by some configurations.
