### ISSUE TITLE
ccm behind firewall (ANT issue)

### ISSUE THREAD

**Issue by pronzato** [pcmanus/ccm#367]
Hi All,

I have ccm working on Windows at home with no issues and its great!

I've been trying to get ccm to work on Windows behind a corp firewall but when 'ccm create' tries to build cassandra, Ant throws the following exception (in last.txt):

maven-ant-tasks-download:
     [echo] Downloading Maven ANT Tasks...
      [get] Getting: http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar
      [get] To: C:\Users\foo\.ccm\repository\2.2.0\build\maven-ant-tasks-2.1.3.jar
      [get] Error getting http://repo2.maven.org/maven2/org/apache/maven/maven-ant-tasks/2.1.3/maven-ant-tasks-2.1.3.jar to C:\Users\foo\.ccm\repository\2.2.0\build\maven-ant-tasks-2.1.3.jar

BUILD FAILED
C:\Users\foo\.ccm\repository\2.2.0\build.xml:254: java.net.UnknownHostException: repo2.maven.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1003)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:951)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at org.apache.tools.ant.taskdefs.Get$GetThread.openConnection(Get.java:728)
	at org.apache.tools.ant.taskdefs.Get$GetThread.get(Get.java:641)
	at org.apache.tools.ant.taskdefs.Get$GetThread.run(Get.java:631)

I'm guessing this is because of the firewall but I'm unable to find a way to pass the proxy info to Ant (tried creating Windows env vars: http_proxy, ANT_OPTS, JAVA_OPT) but nothing seems to work.  I would change the build.xml but it looks like ccm deletes the downloaded version in progress from the repositiory once the error is thrown so I can't update the build.xml (as I assume the build.xml will be in that folder).

Any ideas?

Regards

GP

**Comment by ptnapoleon** [comment]
Instead of using `ccm create -v 2.1.3`, use `ccm create -v binary:2.1.3`, to skip needing to compile C*.

**Comment by pronzato** [comment]
Thanks Philip, that did the trick but now I've hit another issue (which I knew was next).  Work PC doesn't allow me to change the execution policy to unrestricted so I get the error shown below when starting the cluster.

Would you happen to know any other ways to get this to work on Windows for C* 2.1+?

Regards

GP


C:\Python27\Scripts>ccm create test -v binary:2.2.0 -n 3 -s
Downloading http://archive.apache.org/dist/cassandra/2.2.0/apache-cassandra-2.2.0-bin.tar.gz to c:\users\foo\appdata\local\temp\ccm-yh3_fm.tar.gz (27.874MB)
  29228490  [100.00%]
Extracting c:\users\foo\appdata\local\temp\ccm-yh3_fm.tar.gz as version 2.2.0 ...
Current cluster is now: test
Traceback (most recent call last):
  File "C:\Python27\Scripts\ccm.py", line 72, in <module>
    cmd.run()
  File "C:\Python27\lib\site-packages\ccmlib\cmds\cluster_cmds.py", line 173, in run
    if cluster.start(verbose=self.options.debug_log, wait_for_binary_proto=self.options.binary_protocol, jvm_args=self.options.jvm_args, profile_options=profile_options) is None:
  File "C:\Python27\lib\site-packages\ccmlib\cluster.py", line 249, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options)
  File "C:\Python27\lib\site-packages\ccmlib\node.py", line 440, in start
    raise NodeError("PS Execution Policy must be unrestricted when running C* 2.1+")
ccmlib.node.NodeError: PS Execution Policy must be unrestricted when running C* 2.1+

**Comment by ptnapoleon** [comment]
Sorry, but unfortunately CCM really can't run multiple C* nodes at once on Windows without the unrestricted powershell execution policy. You'll need to run C* directly, using only one node.

**Comment by pronzato** [comment]
Was worried that might be the case.

Thanks for all the help.
