### ISSUE TITLE
Can't start nodes when there is a space in the name

### ISSUE THREAD

**Issue by tjake** [pcmanus/ccm#421]
cm create -n 3 -v 2.2.3 "ccm space test"
ccm node1 start
Timed out waiting for pidfile to be filled (current time is 2015-12-04 12:59:53.151992)

**Comment by cormoran** [comment]
Because of cassandra' s [shell script issue - CASSANDRA-11888](https://issues.apache.org/jira/browse/CASSANDRA-11888), there seems to be no simple way to allow spaces in a cluster name.
```
# Tested on Mac OSX
$ python --version
Python 2.7.10
$ ccm create -n 3 'white space' -v 3.11.0
$ ccm start
[node1 ERROR] grep: ~/.ccm/white: No such file or directory
grep: space/node1/conf/jvm.options: No such file or directory
Error parsing arguments! Unknown argument "space/node1/cassandra.pid"
Error starting nodes, see above for details (you can use --verbose for more information)
```

Also, non-ASCII word characters can cause errors in ccm or the cassandra script.
```
$ ccm create -n 3 Japaneseテスト -v 3.11.0
Current cluster is now: Japaneseテスト
$ ccm start
Traceback (most recent call last):
  File "~/Library/Python/2.7/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.8.2', 'ccm')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "~/Library/Python/2.7/lib/python/site-packages/ccm-2.8.2-py2.7.egg/EGG-INFO/scripts/ccm", line 90, in <module>

  File "build/bdist.macosx-10.12-intel/egg/ccmlib/cmds/cluster_cmds.py", line 594, in run
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/cluster.py", line 393, in start
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/node.py", line 622, in start
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/node.py", line 185, in get_env
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/common.py", line 257, in make_cassandra_env
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/common.py", line 200, in replaces_in_file
UnicodeEncodeError: 'ascii' codec can't encode characters in position 44-46: ordinal not in range(128)
```
```
$ ccm create -n 3 '(' -v 3.11.0
Current cluster is now: (
$ ccm start
[node1 ERROR] ~/.ccm/(/node1/bin/cassandra.in.sh: line 23: syntax error near unexpected token `('
~/.ccm/(/node1/bin/cassandra.in.sh: line 23: `	CASSANDRA_CONF=~/.ccm/(/node1/conf'
You must set the CASSANDRA_CONF and CLASSPATH vars
Error starting nodes, see above for details (you can use --verbose for more information)
```
So, it's better to only allow `[a-zA-Z0-9_-]+` in the cluster name.

**Comment by spodkowinski** [comment]
This is slightly annoying, as you won't be able to use a C* version in the cluster name anymore. I have to recreate all clusters named like e.g. `v3.0.x-3n`.

**Comment by ptnapoleon** [comment]
That's fair, we should allow `.` and `-` as well.
