### ISSUE TITLE
Can't create nodes with --config-dir on command line

### ISSUE THREAD

**Issue by mambocab** [pcmanus/ccm#422]
I've reproduced this on Windows on CassCI, and locally on Windows. Whenever I try to create nodes, it tries to do so at a directory that doesn't exist. Specifically, if it's supposed to be in `config-dir/cluster-name/node1`, it seems to create it at `config-dir/cluster-name/node1/config-dir/cluster-name/node1/`, or something like that. Here's the error on Windows:

```
$ ccm create --config-dir ./ccm-dir -v git:cassandra-3.0 test-installation -n 3
http://git-wip-us.apache.org/repos/asf/cassandra.git git:cassandra-3.0
Fetching Cassandra updates...
Current cluster is now: test-installation
Traceback (most recent call last):
  File "/home/mambocab/miniconda/envs/cstar_te/bin/ccm", line 74, in <module>
    cmd.run()
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 179, in run
    cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat)
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/cluster.py", line 179, in populate
    binary_interface=binary)
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/cluster.py", line 185, in create_node
    return Node(name, self, auto_bootstrap, thrift_interface, storage_interface, jmx_port, remote_debug_port, initial_token, save, binary_interface)
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/node.py", line 108, in __init__
    self.import_config_files()
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/node.py", line 1136, in import_config_files
    self._update_config()
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/node.py", line 1226, in _update_config
    os.mkdir(os.path.join(dir_name, dir))
OSError: [Errno 2] No such file or directory: './ccm-dir/test-installation/node1/./ccm-dir/test-installation/node1/data'
```                                                                                                                                                                              

Here's an example on windows:

http://cassci.datastax.com/view/All_Jobs/job/mambocab-scratch_cqlshlib_tests-windows-3.0-paulomotta/44/console

EDIT: by "locally on windows" I mean "locally on Linux".

**Comment by ptnapoleon** [comment]
So this is on cluster create, and not just when adding nodes?

**Comment by mambocab** [comment]
Running `create` adds nodes because I used the `-n` option.

**Comment by ptnapoleon** [comment]
I meant adding nodes one at a time, on an already created cluster.

**Comment by ptnapoleon** [comment]
This is because you're using relative paths on windows, and not absolute paths. The code changes to fix the path reasoning by python on windows are large/gross.

**Comment by mambocab** [comment]
Is the solution more complicated than `os.path.abspath`?

**Comment by mambocab** [comment]
discussed offline: it is.
