### ISSUE TITLE
Can't `ccm remove` clusters with installation directories that no longer exist

### ISSUE THREAD

**Issue by mambocab** [pcmanus/ccm#423]
You can reproduce this with:

```sh
git clone /home/mambocab/cstar_src/cassandra
cd cassandra 
ant
cd ..
ccm create cant-touch-this -n 1 --install-dir cassandra
rm cassandra
rm -rf cassandra
ccm remove cant-touch-this
```

The error you get when this happens is:

```
Traceback (most recent call last):
  File "/home/mambocab/miniconda/envs/cstar_te/bin/ccm", line 74, in <module>
    cmd.run()
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 409, in run
    cluster = ClusterFactory.load(self.path, self.other_cluster)
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/cluster_factory.py", line 28, in load
    if common.isDse(install_dir):
  File "/home/mambocab/miniconda/envs/cstar_te/lib/python2.7/site-packages/ccmlib/common.py", line 354, in isDse
    raise ArgumentError('Installation directory does not contain a bin directory: %s' % install_dir)
ccmlib.common.ArgumentError: Installation directory does not contain a bin directory: /home/mambocab/tmp/scratch-1449518495/cassandra
```

Seems silly to require the directory you're removing to be a valid C\* directory when the goal is to remove it, especially since `ccm remove` can be part of the procedure to get rid of a borked install.

**Comment by ptnapoleon** [comment]
Hmm. I see the issue, but an easy fix doesn't come to mind/

**Comment by mambocab** [comment]
Why does removing a cluster call `isDse`? Maybe to stop any running processes? If that's the case, you could just let that step fail and remove the directory regardless. Or does that code run regardless of the command?

**Comment by mambocab** [comment]
Any further thoughts on this?

**Comment by ptnapoleon** [comment]
Nope. Still isn't urgent and I am still very busy.

**Comment by djbowers** [comment]
So I can't quite figure out an elegant solution to this problem right now. When Philip gets back from vacation, we can discuss.
