### ISSUE TITLE
Decommissioning a C* node fails

### ISSUE THREAD

**Issue by jorgebay** [pcmanus/ccm#442]
Decommission of a node fails:

```bash
ccm create test -i 127.0.0. -v 2.1.11 
ccm populate -n 2
ccm start --wait-for-binary-proto
ccm node2 decommission
```

```
ccmlib.node.NodetoolError: Nodetool command '/Users/jorge/.ccm/repository/2.0.17/bin/nodetool -h localhost -p 7200 decommission' failed; exit status: 1;
Exception in thread "main" java.io.IOError: java.io.IOException: Thread signal failed
	at org.apache.cassandra.net.MessagingService.shutdown(MessagingService.java:746)
	at org.apache.cassandra.service.StorageService$5.run(StorageService.java:3004)
	at org.apache.cassandra.service.StorageService.unbootstrap(StorageService.java:3073)
	at org.apache.cassandra.service.StorageService.decommission(StorageService.java:3010)
```
The node correctly leaves the ring, though. Cassandra log:
```
INFO [Thread-2] 2016-01-29 15:34:15,359 ThriftServer.java (line 135) Listening for thrift clients...
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:16,351 StorageService.java (line 981) LEAVING: sleeping 30000 ms for batch 
processing and pending range setup
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,352 StorageService.java (line 981) LEAVING: replaying batch log and streaming data to other nodes
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,360 StreamResultFuture.java (line 87) [Stream #71a1e410-c695-11e5-9a65-130aecf8e504] Executing streaming plan for Unbootstrap
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,360 StorageService.java (line 981) LEAVING: streaming hints to other nodes
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,366 StreamResultFuture.java (line 87) [Stream #71a31c90-c695-11e5-9a65-130aecf8e504] Executing streaming plan for Hints
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,366 StreamResultFuture.java (line 91) [Stream #71a31c90-c695-11e5-9a65-130aecf8e504] Beginning stream session with /127.0.0.1
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,366 StreamSession.java (line 203) [Stream #71a31c90-c695-11e5-9a65-130aecf8e504] Session does not have any tasks.
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,367 StreamResultFuture.java (line 186) [Stream #71a31c90-c695-11e5-9a65-130aecf8e504] Session with /127.0.0.1 is complete
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,369 StreamResultFuture.java (line 220) [Stream #71a31c90-c695-11e5-9a65-130aecf8e504] All sessions completed
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,370 ColumnFamilyStore.java (line 808) Enqueuing flush of Memtable-local@1236339041(50/500 serialized/live bytes, 2 ops)
 INFO [FlushWriter:1] 2016-01-29 15:34:46,370 Memtable.java (line 362) Writing Memtable-local@1236339041(50/500 serialized/live bytes, 2 ops)
INFO [FlushWriter:1] 2016-01-29 15:34:46,377 Memtable.java (line 402) Completed flushing /Users/jorge/.ccm/test/node2/data0/system/local/system-local-jb-6-Data.db (77 bytes) for commitlog position ReplayPosition(segmentId=1454078046635, position=96724)
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,378 StorageService.java (line 1795) Removing tokens [0] for /127.0.0.2
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:34:46,381 StorageService.java (line 3021) Announcing that I have left the ring for 30000ms
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:35:16,382 ThriftServer.java (line 141) Stop listening to thrift clients
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:35:16,393 Server.java (line 184) Stop listening for CQL clients
 WARN [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:35:16,393 Gossiper.java (line 1439) No local state or state is in silent shutdown, not announcing shutdown
 INFO [RMI TCP Connection(4)-127.0.0.1] 2016-01-29 15:35:16,394 MessagingService.java (line 731) Waiting for messaging service to quiesce
 INFO [ACCEPT-/127.0.0.2] 2016-01-29 15:35:16,394 MessagingService.java (line 1001) MessagingService has terminated the accept() thread

```
Under OS X with C* 2.0, 2.1 and 2.2. Tested on Windows for C* 2.0

cc @landim

**Comment by mambocab** [comment]
> Tested on Windows for C* 2.0

Just to confirm, you get the same result on Windows?

I've run this on Ubuntu and did not see this error:

```
+ ccm create test -i 127.0.0. -v 2.1.11
Current cluster is now: test
+ ccm populate -n 2
+ ccm start --wait-for-binary-proto
+ ccm node2 decommission
```

**Comment by landim** [comment]
It happened in windows too. The decommission cmd do not stops the node, it continues running.

**Comment by jorgebay** [comment]
On Windows the behaviour is different, with C* 2.1 it works as expected.
With C* 2.0, the `ccm node2 decommission` command exits with `0` but the node does not start shutdown.

**Comment by jorgebay** [comment]
Just to note that fixing it for Windows (with C* 2.0) is a higher priority for me, as it's going to be used for C# driver CI.

**Comment by ptnapoleon** [comment]
All CCM does here is call `nodetool decommission`. I can confirm that just running C*, I still see the nodes fail to stop on the listed operating systems after a decom. I think you are seeing a C* bug, not a CCM problem. Open an apache jira for C*.
