### ISSUE TITLE
`ccm create -n ...` fails: TypeError: 'bool' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by tupton** [pcmanus/ccm#443]
```
❯ ccm create dse476 --dse --dse-username=<> --dse-password=<> -n 1 -v 4.7.6
Downloading http://downloads.datastax.com/enterprise/dse-4.7.6-bin.tar.gz to /var/folders/rv/nw5w5tjj4p15z5t9rkmc4xbc0000gn/T/ccm-cNA991.tar.gz (468.728MB)
 491497378  [100.00%]
Extracting /var/folders/rv/nw5w5tjj4p15z5t9rkmc4xbc0000gn/T/ccm-cNA991.tar.gz as version 4.7.6 ...
Current cluster is now: dse476
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 74, in <module>
    cmd.run()
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 189, in run
    cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat, install_byteman=self.options.install_byteman)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cluster.py", line 185, in populate
    binary_interface=binary)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/dse_cluster.py", line 62, in create_node
    return DseNode(name, self, auto_bootstrap, thrift_interface, storage_interface, jmx_port, remote_debug_port, byteman_port, initial_token, save, binary_interface)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/dse_node.py", line 26, in __init__
    super(DseNode, self).__init__(name, cluster, auto_bootstrap, thrift_interface, storage_interface, jmx_port, remote_debug_port, initial_token, save, binary_interface, byteman_port)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/node.py", line 95, in __init__
    'binary': common.normalize_interface(binary_interface)}
  File "/usr/local/lib/python2.7/site-packages/ccmlib/common.py", line 443, in normalize_interface
    ip = itf[0]
TypeError: 'bool' object has no attribute '__getitem__'
```

I'm on the latest pip version of ccm if that matters.

**Comment by tupton** [comment]
Updating to the latest master seems to fix this issue.

**Comment by ptnapoleon** [comment]
New pip release cut from master.
