### ISSUE TITLE
Error when using ccm commands after adding node: TypeError: create_node() got multiple values for keyword argument 'byteman_port'

### ISSUE THREAD

**Issue by tupton** [pcmanus/ccm#444]
```
❯ ccm create dse476 --dse --dse-username= --dse-password= -n 1 -v 4.7.6
# fails due to #443
❯ ccm add node1 --dse -i 127.0.0.1 -j 7199 -t 127.0.0.1 -l 127.0.0.1 --binary-itf 127.0.0.1 --remote-debug-port 0 -n 0
❯ ccm status
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 72, in <module>
    cmd.validate(parser, options, args)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 385, in validate
    Cmd.validate(self, parser, options, args, load_cluster=True)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cmds/command.py", line 68, in validate
    self.cluster = self._load_current_cluster()
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cmds/command.py", line 97, in _load_current_cluster
    return ClusterFactory.load(self.path, name)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/cluster_factory.py", line 48, in load
    cluster.nodes[node_name] = Node.load(cluster_path, node_name, cluster)
  File "/usr/local/lib/python2.7/site-packages/ccmlib/node.py", line 135, in load
    node = cluster.create_node(data['name'], data['auto_bootstrap'], tuple(itf['thrift']), tuple(itf['storage']), data['jmx_port'], remote_debug_port, initial_token, save=False, binary_interface=binary_interface, byteman_port=data['byteman_port'])
TypeError: create_node() got multiple values for keyword argument 'byteman_port'
```

I'm on the latest pip version of ccm. Note that the initial `create -n 1` command fails because of #443. The above stack trace occurs with `ccm start` as well as `status`.

**Comment by tupton** [comment]
This issue is fixed when installing and running from the latest master.

Can we get another pip release? Also, is it possible to tag releases beforehand? It's very confusing that both the latest master and the pip registry say 2.1.2.

**Comment by ptnapoleon** [comment]
New pip release cut from master.
