### ISSUE TITLE
Can't start cluster with more than 1 node in windows for C* version 2.2.5 

### ISSUE THREAD

**Issue by landim** [pcmanus/ccm#458]
I ran the following commands:
ccm create mytest -i 127.0.0. -v 2.2.5
ccm populate -n 2
ccm start --wait-for-binary-proto --quiet-windows

and got the error:
Traceback (most recent call last):
  File "C:\Python27\Scripts\ccm.py", line 74, in <module>
    cmd.run()
  File "C:\Python27\lib\site-packages\ccmlib\cmds\cluster_cmds.py", line 581, in run
    allow_root=self.options.allow_root) is None:
  File "C:\Python27\lib\site-packages\ccmlib\cluster.py", line 308, in start
    node.watch_log_for_alive(other_node, from_mark=mark)
  File "C:\Python27\lib\site-packages\ccmlib\node.py", line 443, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "C:\Python27\lib\site-packages\ccmlib\node.py", line 411, in watch_log_for
    raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str([e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 01 Mar 2016 12:18:02 [node1] Missing: ['127.0.0.2.* now UP']:
INFO  [main] 2016-03-01 09:15:46,321 YamlConfigura.....
See system.log for remainder

[system.log.txt](https://github.com/pcmanus/ccm/files/152917/system.log.txt)

It works for c* 2.2.4 though.

**Comment by ptnapoleon** [comment]
I'm able to start a two node cluster just fine. How often does this happen? Can you attach the system.log for node1? I don't see anything wrong with node2, which you attached.

**Comment by dins2k2** [comment]
Hello,

I tried to add a new node in a cluster with one node already, getting the same error as **landim**

$ ccm status
Cluster: 'cluster2' 
n1: UP

$ ccm add n2 -i 127.0.1.2 -j 7200

$ ccm status
Cluster: 'cluster2'
n1: UP
n2: DOWN (Not initialized)

$ ccm n2 start

Started: n2 with pid: 3004
Traceback (most recent call last):
  File "E:\Studies\Cassandra\ccm\ccm-master\ccm.py", line 74, in <module>
    cmd.run()
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\cmds\node_cmds.py", line 206, in run
    allow_root=self.options.allow_root)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\node.py", line 597, in start
    node.watch_log_for_alive(self, from_mark=mark)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\node.py", line 449, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\node.py", line 417, in watch_log_for
    raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str([e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 20 Mar 2016 05:22:05 [n1] Missing: ['127.0.1.2.* now UP']:
.....
See system.log for remainder

I could not see any system.log file on node2(n2) logs directory. I'm not sure how and where the above error logs!!!

Attaching the node1(n1) system.log file.

[system.log.txt](https://github.com/pcmanus/ccm/files/181184/system.log.txt)

Note : **ccm populate -n** works perfectly. Throws error for **ccm add**.

Thanks,
Dinesh

**Comment by jabs76** [comment]
it could be your jdk version or C* version not compatible.
In my case when I used java '1.8.0_161-b12' with C* '3.7' I got the same error.
But with C* '3.11.2' it worked fine.

**Comment by AreWeThereYet** [comment]
Just started happening to me.

$ ccm start
Traceback (most recent call last):
  File "/usr/local/Cellar/ccm/3.1.4/libexec/bin/ccm", line 105, in <module>
    cmd.run()
  File "/usr/local/Cellar/ccm/3.1.4/libexec/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 491, in run
    allow_root=self.options.allow_root) is None:
  File "/usr/local/Cellar/ccm/3.1.4/libexec/lib/python2.7/site-packages/ccmlib/cluster.py", line 428, in start
    node.watch_log_for_alive(other_node, from_mark=mark)
  File "/usr/local/Cellar/ccm/3.1.4/libexec/lib/python2.7/site-packages/ccmlib/node.py", line 527, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/usr/local/Cellar/ccm/3.1.4/libexec/lib/python2.7/site-packages/ccmlib/node.py", line 495, in watch_log_for
    raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str([e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 15 Jun 2018 02:02:19 [node1] Missing: ['172.10.10.3.* now UP']:
INFO  [main] 2018-06-14 22:00:17,124 Config.java:4.....
See system.log for remainder

$ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)




Any suggestions desperately welcome

**Comment by PuscasSebi** [comment]
no update ?

**Comment by AreWeThereYet** [comment]
Had to blow away and recreate.  Wasn't possible to update C*

**Comment by HaoQinC** [comment]
I also encountered this issue with C* version 2.2.17, 3.0.0 and 3.11. It's ok to add the first node, however the start of the second node is always failed, in error log it was said 
`ERROR: transport error 202: bind failed: Address already in use
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]`

The JMX port was confirmed not in using, and the IP neither. I am not sure what else could result in this issue.
