### ISSUE TITLE
Upgrade / Downgrade of node leaves previous jamm jar version in configs

### ISSUE THREAD

**Issue by mshuler** [pcmanus/ccm#463]
While adding sstableupgrade_test in dtest, I found that when the jamm jar version changes between 2.0 and 2.1 Cassandra branches, CCM does not handle the configuration updates fully during upgrade/downgrade of a node, leaving the old jamm jar version in the configs. I'll work on repro steps and add them here, but I believe that this comes from the env setup in ccmlib/common.py.

**Comment by mshuler** [comment]
Repro steps:

```
ccm create -v git:cassandra-2.0 -n 1 jamm-upgrade-test
ccm start
ccm node1 status
ccm stop
ccm setdir -v git:cassandra-2.1
ccm start
ccm node1 status
```

This fails to find the jamm-0.3.0.jar installed in cassandra-2.1

```
mshuler@hana:~$ ccm create -v git:cassandra-2.0 -n 1 jamm-upgrade-test
http://git-wip-us.apache.org/repos/asf/cassandra.git git:cassandra-2.0
Fetching Cassandra updates...
Current cluster is now: jamm-upgrade-test
mshuler@hana:~$ ccm start
mshuler@hana:~$ ccm node1 status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Owns (effective)  Host ID                               Token                                    Rack
UN  127.0.0.1  41.22 KB   100.0%            daf17e83-99f8-42ea-a357-8b429ee78b04  -9223372036854775808                     rack1

mshuler@hana:~$ ccm stop
mshuler@hana:~$ ccm setdir -v git:cassandra-2.1
http://git-wip-us.apache.org/repos/asf/cassandra.git git:cassandra-2.1
Fetching Cassandra updates...
mshuler@hana:~$ ccm start
mshuler@hana:~$ ccm node1 status
Traceback (most recent call last):
  File "/home/mshuler/git/ccm/ccm", line 74, in <module>
    cmd.run()
  File "/home/mshuler/git/ccm/ccmlib/cmds/node_cmds.py", line 255, in run
    stdout, stderr = self.node.nodetool(self.nodetool_cmd + " " + " ".join((self.args[1:])))
  File "/home/mshuler/git/ccm/ccmlib/node.py", line 699, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/home/mshuler/.ccm/repository/gitCOLONcassandra-2.1/bin/nodetool -h localhost -p 7100 status' failed; exit status: 1; stdout: Error occurred during initialization of VM
agent library failed to init: instrument
; stderr: Error opening zip file or JAR manifest missing : /home/mshuler/.ccm/repository/gitCOLONcassandra-2.1/lib/jamm-0.2.5.jar

mshuler@hana:~$
```

**Comment by mshuler** [comment]
https://github.com/pcmanus/ccm/pull/279/files#diff-e19f0f0ec871623be418f8c4e97f9f46R138

Reverting the above commit is probably the fix here - @ptnapoleon do you have an opinion?

**Comment by iamaleksey** [comment]
Only [this line](https://github.com/pcmanus/ccm/pull/279/files#diff-e19f0f0ec871623be418f8c4e97f9f46R138) is really an issue: it leaves the original cassandra.in.sh no matter how many times we upgrade or downgrade, that means old jamm dependency stays there if you started with 2.0, forever. Making it unconditional again would fix the problem.
