### ISSUE TITLE
ccm stress on windows 10 - AuthenticationException

### ISSUE THREAD

**Issue by dins2k2** [pcmanus/ccm#471]
Hello,

While trying ccm stress on windows 10, getting the below error. Error seems authentication needs to be provided in the command. But I don't see those stress options. Or do I need to set it up anywhere in any of the config files?

$ ccm node4 stress write n=50000 -rate threads=4

INFO  14:06:41 Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
java.lang.RuntimeException: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /127.0.0.4:9042: Host /127.0.0.4:9042 requires authentication, but no authenticator found in Cluster configuration
        at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:198)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:205)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:55)
        at org.apache.cassandra.stress.Stress.main(Stress.java:117)
Caused by: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /127.0.0.4:9042: Host /127.0.0.4:9042 requires authentication, but no authenticator found in Cluster configuration
        at com.datastax.driver.core.AuthProvider$1.newAuthenticator(AuthProvider.java:39)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:259)
        at com.datastax.driver.core.Connection$5.apply(Connection.java:243)
        at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:906)
        at com.google.common.util.concurrent.Futures$1$1.run(Futures.java:635)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at com.google.common.util.concurrent.Futures$1.run(Futures.java:632)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:457)
        at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
        at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
        at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1178)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1008)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:931)
        at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:254)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:242)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
        at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
        at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
        at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)

Thanks,
Dinesh

**Comment by dins2k2** [comment]
Hello,

I found out the solution.

I have setup Authenticator field as PasswodAuthenticator in cassandra.yaml file. So, stress command throws the above error if you don't provide the username & password like below using -mode option. For more details on stress commands & options, check [here](http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCStress_t.html).

**$ ccm node4 stress write n=10000 cl=one -mode native cql3 user=cassandra password=cassandra**

Thanks,
Dinesh
