### ISSUE TITLE
Unable to add new node to existing cluster facing 

### ISSUE THREAD

**Issue by velpulavijay** [pcmanus/ccm#474]
Unable to add new node to existing cluster facing below error .

ERROR [main] 2016-03-18 10:29:30,328 CassandraDaemon.java:692 - Cannot start node if snitch's data center (datacenter1) differs from previous data center (East_DC). Please fix the snitch configuration, decommission and rebootstrap this node or use the flag

In Cassandra.YAMIL config file even we made necessary changes to endpoint_snitch property ( from simplesnitch to   GossipingPropertyFileSnitch)  and autobootstrap= true  still I am  facing same issue .

But only after deleting data  in all nodes in same cluster  , new node was able to  add and start in the  cluster . Is there any way we can resolve this issue without deleting data

$ ccm start
Started: node1 with pid: 19212
Started: node3 with pid: 16392
Traceback (most recent call last):
  File "C:\CCM\ccm-master\ccm-master\ccm.py", line 74, in <module>
    cmd.run()
  File "C:\CCM\ccm-master\ccm-master\ccmlib\cmds\cluster_cmds.py", line 583, in run
    allow_root=self.options.allow_root) is None:
  File "C:\CCM\ccm-master\ccm-master\ccmlib\cluster.py", line 335, in start
    p = node.start(update_pid=False, jvm_args=jvm_args, profile_options=profile_options, verbose=verbose, quiet_start=quiet_start, allow_root=allow_root)
  File "C:\CCM\ccm-master\ccm-master\ccmlib\node.py", line 597, in start
    node.watch_log_for_alive(self, from_mark=mark)
  File "C:\CCM\ccm-master\ccm-master\ccmlib\node.py", line 449, in watch_log_for_alive
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "C:\CCM\ccm-master\ccm-master\ccmlib\node.py", line 417, in watch_log_for
    raise TimeoutError(time.strftime("%d %b %Y %H:%M:%S", time.gmtime()) + " [" + self.name + "] Missing: " + str([e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 18 Mar 2016 15:31:04 [node1] Missing: ['127.0.0.3.* now UP']:
INFO  [main] 2016-03-18 10:28:56,281 YamlConfigura.....
See system.log for remainder

$ ccm node1 version

ReleaseVersion: 3.0.4 
CCM on windows 7

**Comment by ishaansutaria119** [comment]
Hi I have a similar issue. Were you able to resolve it?
