### ISSUE TITLE
nodetool repair - stdout: nodetool: Keyspace does not exist

### ISSUE THREAD

**Issue by dins2k2** [pcmanus/ccm#486]
Hello,

When we try nodetool repair, options are working only with keyspace not with **all keyspace(default)**.

```
$ ccm node6 nodetool "repair test -dcpar"

[2016-03-31 10:21:32,851] Nothing to repair for keyspace 'test'
```

Getting below error if I don't give any keyspace name. As per DataStax doc, by default if don't give any keyspace, it should repair for all the keyspaces. 

```
$ ccm node6 nodetool "repair -inc -hosts 127.0.1.4 127.0.1.5"
Traceback (most recent call last):
  File "C:\Dinesh\ccm\ccm-master\ccm.py", line 74, in <module>
    cmd.run()
  File "C:\Dinesh\ccm\ccm-master\ccmlib\cmds\node_cmds.py", line 267, in run
    stdout, stderr = self.node.nodetool(" ".join(self.args[1:]))
  File "C:\Dinesh\ccm\ccm-master\ccmlib\node.py", line 699, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command 'C:\Users\Dinesh\.ccm\repository\3.0.3\bin\nodetool.bat 
-h localhost -p 7600 repair -inc -hosts 127.0.1.4 127.0.1.5' failed; exit status: 1; 
stdout: **nodetool: Keyspace [-inc] does not exist**.
See 'nodetool help' or 'nodetool help <command>'.
```

Any suggestions?

**CCM on Window 10; C* : 3.0.3**

Thanks,
Dinesh

**Comment by mambocab** [comment]
This is more a question about C\* than about CCM. Make sure you're reading documentation for the version of C\* you're using, then ask for help on IRC or the user mailing list as described at the bottom of this page:

http://cassandra.apache.org/

**Comment by dins2k2** [comment]
@mambocab Thanks for the suggestion. But, I get this error only when I'm trying in CCM. I just want to know the workaround or am I missing anything.

**Comment by ptnapoleon** [comment]
@dins2k2 `-inc` is not a valid option on 3.0.3, so I'm not sure that you are only getting this message with CCM

**Comment by dins2k2** [comment]
These are the options I tried.

```
$ ccm node6 nodetool "repair -dc dc3" 
  
[2016-03-30 11:24:02,958] Nothing to repair for keyspace 'test' 
[2016-03-30 11:24:02,965] Nothing to repair for keyspace 'system_auth' 
[2016-03-30 11:24:02,977] Starting repair command #2, repairing keyspace system_traces with repair options (parallelism: parallel, primary range: false, incremental: true, job threads: 1, ColumnFamilies: [], dataCenters: [dc3], hosts: [], # of ranges: 2) 
[2016-03-30 11:24:03,014] Repair completed successfully 
[2016-03-30 11:24:03,020] Repair command #2 finished in 0 seconds 

$ ccm node6 nodetool "repair test -host 127.0.1.4 127.0.1.5"  
[2016-03-31 10:15:23,756] Nothing to repair for keyspace 'test' 

$ ccm node6 nodetool "repair test -inc"  
[2016-03-31 10:13:45,538] Nothing to repair for keyspace 'test' 

$ ccm node6 nodetool "repair test -pr"                                                                                           [2016-03-31 10:19:25,302] Nothing to repair for keyspace 'test'                                                                                               

$ ccm node6 nodetool "repair test -pr -inc"
[2016-03-31 10:19:47,481] Nothing to repair for keyspace 'test'                                                                                                                                                         

$ ccm node6 nodetool "repair test -pr -seq"
[2016-03-31 10:19:55,661] Nothing to repair for keyspace 'test'                                                                                                                                                         

$ ccm node6 nodetool "repair test -pr -par" 
[2016-03-31 10:20:10,057] Nothing to repair for keyspace 'test'                                                                                       

$ ccm node6 nodetool "repair test -dcpar dc1 dc2"
[2016-03-31 14:20:27,982] Nothing to repair for keyspace 'test'  

$ ccm node6 nodetool "repair -inc -hosts 127.0.1.4 127.0.1.5"
Traceback (most recent call last):
  File "C:\Dinesh\ccm\ccm-master\ccm.py", line 74, in <module>
    cmd.run()
  File "C:\Dinesh\ccm\ccm-master\ccmlib\cmds\node_cmds.py", line 267, in run
    stdout, stderr = self.node.nodetool(" ".join(self.args[1:]))
  File "C:\Dinesh\ccm\ccm-master\ccmlib\node.py", line 699, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command 'C:\Users\Dinesh\.ccm\repository\3.0.3\bin\
nodetool.bat -h localhost -p 7600 repair -inc -hosts 127.0.1.4 127.0.1.5' failed; 
exit status: 1; stdout: nodetool: Keyspace [-inc] does not exist.
See 'nodetool help' or 'nodetool help <command>'.

```


If I remove keyspace(test) I get the above error.

**Comment by ptnapoleon** [comment]
Again, I don't see the issue. `nodetool repair -inc -hosts 127.0.1.4 127.0.1.5` will give the exact same error message on a normal C* installation, because it is an invalid set of options. This is not a CCM bug.

**Comment by dins2k2** [comment]
Thanks for the clarification and my apologies for asking non CCM questions.
