### ISSUE TITLE
2.1.14 breaks Python 3 support

### ISSUE THREAD

**Issue by LaurensBER** [pcmanus/ccm#492]
```
Traceback (most recent call last):
  File "venv/bin/ccm", line 74, in <module>
    cmd.run()
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/cmds/cluster_cmds.py", line 200, in run
    cluster.populate(self.nodes, self.options.debug, use_vnodes=self.options.vnodes, ipprefix=self.options.ipprefix, ipformat=self.options.ipformat, install_byteman=self.options.install_byteman)
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/cluster.py", line 223, in populate
    binary_interface=binary)
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/cluster.py", line 229, in create_node
    return Node(name, self, auto_bootstrap, thrift_interface, storage_interface, jmx_port, remote_debug_port, initial_token, save, binary_interface, byteman_port)
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/node.py", line 110, in __init__
    self.import_config_files()
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/node.py", line 1224, in import_config_files
    self.__update_yaml()
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/node.py", line 1379, in __update_yaml
    self.__config_options, delete_empty=False)
  File "/home/laurens/dev/diataal/venv/lib/python3.4/site-packages/ccmlib/common.py", line 616, in merge_configuration
    for k, v in changes.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

Reverting back to 2.1.13 solves the issue

**Comment by ptnapoleon** [comment]
I just released 2.1.5, which should resolve the issue.
