### ISSUE TITLE
ccm dse installation - WindowsError: [Error 206] The filename or extension is too long

### ISSUE THREAD

**Issue by dins2k2** [pcmanus/ccm#496]
Hello,

Tried installing dse 4.6.0, getting this error 
**WindowsError: [Error 206] The filename or extension is too long.**

```
$ ccm create --dse -v 4.6.0 --dse-username=username@mail --dse-password=passForDse -o 5.0.2 -n 3:2:1 dse460
Downloading http://downloads.datastax.com/enterprise/dse-4.6.0-bin.tar.gz to c:\users\dins2\appdata\local\temp\ccm-yvmspj.tar.gz (511.738MB)
 536595851  [100.00%]
Extracting c:\users\dins2\appdata\local\temp\ccm-yvmspj.tar.gz as version 4.6.0 ...
Cannot create cluster: [Error 206] The filename or extension is too long: 'C:\\Users\\dins2\\.ccm\\repository\\dse-4.6.0\\demos\\http_receiver\\HttpSparkStream\\target\\scala-2.10\\cache\\httpsparkstream\\global\\assembly\\01f66868d530f157b49b1d5e52cc2fceffd44abb_9aae4cb1802537d604e03688cab744ff47b31a7d\\scala\\collection\\parallel\\immutable'
Traceback (most recent call last):
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\cmds\cluster_cmds.py", line 156, in run
    cluster = DseCluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, dse_username=self.options.dse_username, dse_password=self.options.dse_password, dse_credentials_file=self.options.dse_credentials_file, opscenter=self.options.opscenter, verbose=True)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\dse_cluster.py", line 31, in __init__
    super(DseCluster, self).__init__(path, name, partitioner, install_dir, create_directory, version, verbose)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\cluster.py", line 63, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\dse_cluster.py", line 38, in load_from_repository
    return repository.setup_dse(version, self.dse_username, self.dse_password, verbose)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\repository.py", line 87, in setup_dse
    download_dse_version(version, username, password, verbose=verbose)
  File "E:\Studies\Cassandra\ccm\ccm-master\ccmlib\repository.py", line 220, in download_dse_version
    tar.extractall(path=__get_dir())
  File "C:\Program Files\Python27\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Program Files\Python27\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Program Files\Python27\lib\tarfile.py", line 2193, in _extract_member
    self.makedir(tarinfo, targetpath)
  File "C:\Program Files\Python27\lib\tarfile.py", line 2221, in makedir
    os.mkdir(targetpath, 0700)
```
**WindowsError: [Error 206] The filename or extension is too long: 'C:\\Users\\dins2\\.ccm\\repository\\dse-4.6.0\\demos\\http_receiver\\HttpSparkStream\\target\\scala-2.10\\cache\\httpsparkstream\\global\\assembly\\01f66868d530f157b49b1d5e52cc2fceffd44abb_9aae4cb1802537d604e03688cab744ff47b31a7d\\scala\\collection\\parallel\\immutable'**

**CCM on Windows 10**

Thanks,
Dinesh

**Comment by ptnapoleon** [comment]
DSE does not support being run on Windows, only open source Apache Cassandra.

**Comment by dins2k2** [comment]
@ptnapoleon Thanks. I have successfully installed it in Ubuntu.
