### ISSUE TITLE
`sudo setup.py install` installs ccm egg only readable by root

### ISSUE THREAD

**Issue by samoverton** [pcmanus/ccm#507]
Using Ubuntu 16.04 with default python installation:

```
$ sudo python setup.py install
$ ccm
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==2.1.7', 'ccm')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ccm==2.1.7' distribution was not found and is required by the application
$ sudo ccm
Missing arguments
Usage:
  ccm <cluster_cmd> [options]
  ccm <node_name> <node_cmd> [options]

Where <cluster_cmd> is one of
  create         Create a new cluster
  add            Add a new node to the current cluster
  populate       Add a group of new nodes with default options
  list           List existing clusters
<snip/>
$ ls -l /usr/local/lib/python2.7/dist-packages/ccm-2.1.7-py2.7.egg
-rwxrwx--- 1 root staff 158742 Jun  7 14:24 /usr/local/lib/python2.7/dist-packages/ccm-2.1.7-py2.7.egg
```

**Comment by samoverton** [comment]
On a second look, this is more likely to be a system configuration issue rather than an issue with ccm's use of setuptools. Still, this was on an ubuntu base image so it's likely to be a commonly encountered problem.

**Comment by ptnapoleon** [comment]
I don't think you should be using sudo to install ccm. Is there some problem that occurs when you try to install without it?

**Comment by samoverton** [comment]
```
$ python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-32463.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.

```
The ccm README also says:

> ccm uses python distutils so from the source directory run:
> 
> `sudo ./setup.py install
`

**Comment by ptnapoleon** [comment]
Well, you've got me on the README. That should definitely be improved. I believe setup.py has a --user argument that lets you not need sudo, but it doesn't install it system-wide, which may be of assistance to you
