### ISSUE TITLE
Conflict when running DSE CCM nodes on machine with DSE installed

### ISSUE THREAD

**Issue by beccam** [pcmanus/ccm#521]
I'm trying to run a single DSE CCM node (v 4.8.8) on a virtual machine. This VM also has package install of DSE 4.8.8. Since the package install of DSE starts up as the VM starts, I make sure it's shut down:

```
service dse stop
``` 

I create the DSE CCM cluster in such a way:

```
ccm create test --dse --dse-username=x --dse-password=x -v 4.8.8 -n 1 
```

And start up CCM:

```
 ccm start --verbose
```
I then get the following error:

```
Found multiple DSE core jar files in /root/.ccm/repository/4.8.8/lib /root/.ccm/repository/4.8.8/resources/dse/lib /usr/share/dse /usr/share/dse/common . Please make sure there is only one.
```

**Comment by ptnapoleon** [comment]
@mike-tr-adamson Is this something we're able to support?

**Comment by mike-tr-adamson** [comment]
@ptnapoleon I'll take a look and let you know. We ought to be able to run if the installed DSE on the VM isn't running.

**Comment by mike-tr-adamson** [comment]
@beccam I am slightly wary of pushing a fix for this without a lot more investigation but I do have a workaround in the mean time:
```
export DSE_LIB "/root/.ccm/repository/4.8.8/lib /root/.ccm/repository/4.8.8/resources/dse/lib"
ccm start
```
This specifically sets the DSE_LIB and stops the launch script for looking from alternative locations.

**Comment by beccam** [comment]
@mike-tr-adamson Looks like we are getting close, but when I try to run 2 nodes, I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 86, in <module>
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/cmds/node_cmds.py", line 267, in run
    stdout, stderr = self.node.nodetool(" ".join(self.args[1:]))
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/dse_node.py", line 264, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/root/.ccm/repository/4.8.8/bin/nodetool -h localhost -p 7100 status' failed; exit status: 1; stdout: Location pointed by DSERC_ENV not readable: 
```
