### ISSUE TITLE
ccm node1 cqlsh couldn't start cql shell on windows

### ISSUE THREAD

**Issue by daiyueweng** [pcmanus/ccm#526]
Hi, I tried to create 3 nodes in a cluster using

`ccm create -v 2.1.13 -n 3 mycluster`

which created 3 nodes, but when I tried 

`ccm node1 cqlsh`

a command prompt popped up and quickly closed. No CQL shell was opened. I am wondering how to open up a shell on a node. All the nodes were UN.

**Comment by ptnapoleon** [comment]
This should have been enough. Thanks for the report. I'll look into it, but it won't be until after the holiday. As a workaround, you should be able to run cqlsh out of a regular 2.1.13 installation of C*.

**Comment by dins2k2** [comment]
Even I had this issue. If you have configured the **authenticator: PasswordAuthenticator** in **cassandra.yaml** file, you need to mention the usernmae and password while getting into CQLSH like below.

`$ ccm node1 cqlsh -u cassandra -p cassandra`

where **-u cassandra -p cassandra** are default cassandra credentials.

I tried to reproduce the same issue in 2.1.13, but I am able to get into CQLSH. By default the **authenticator : AllowAllAuthenticator** is configured in **cassandra.yaml** file.

HTH

Thanks,
Dinesh

**Comment by adelinedepaepe** [comment]
Hi,
I have the same problem with cassandra 2.1.22.
I get the error: 

`C:\windows\system32>ccm node1 cqlsh                                                                                     Traceback (most recent call last):                                                                                        File "C:\Users\Administrateur\AppData\Local\Programs\Python\Python39\scripts\ccm.py", line 112, in <module>               cmd.run()                                                                                                             File "C:\Python27\lib\site-packages\ccmlib\cmds\node_cmds.py", line 337, in run                                           self.node.run_cqlsh(self.options.cmds, self.cqlsh_options)                                                            File "C:\Python27\lib\site-packages\ccmlib\node.py", line 916, in run_cqlsh                                               p = self.run_cqlsh_process(cmds, cqlsh_options)                                                                       File "C:\Python27\lib\site-packages\ccmlib\node.py", line 913, in run_cqlsh_process                                       return p                                                                                                            UnboundLocalError: local variable 'p' referenced before assignment `

Could you help me?

**Comment by Mezzzer** [comment]
I have the same problem as adelinedepaepe.
