### ISSUE TITLE
ccm start get stuck 

### ISSUE THREAD

**Issue by MarcMagnin** [pcmanus/ccm#595]
Hi,

Thanks for ccm, that's a great tool!
Lately I got an issue where it get stuck when I call ccm start against DSE (regardless of the cluster selected).
When I stop the process it provides the following:
```shell
root@MarcUbuntu16:~# ccm start
^CTraceback (most recent call last):
  File "/usr/local/bin/ccm", line 90, in <module>
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/cmds/cluster_cmds.py", line 594, in run
    allow_root=self.options.allow_root) is None:
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/dse_cluster.py", line 71, in start
    started = super(DseCluster, self).start(no_wait, verbose, wait_for_binary_proto, wait_other_notice, jvm_args, profile_options, quiet_start=quiet_start, allow_root=allow_root)
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/cluster.py", line 409, in start
    node.watch_log_for(start_message, timeout=60, process=p, verbose=verbose, from_mark=mark)
  File "/usr/local/lib/python2.7/dist-packages/ccmlib/node.py", line 434, in watch_log_for
    time.sleep(.5)
KeyboardInterrupt
```
Nothing get written in cassandra logs.
Many thanks for the help.

### Python version
2.7.12

**Comment by ptnapoleon** [comment]
Hi @MarcMagnin, could you provide all of the steps you took prior to getting to this `ccm start`, notably the cluster create command?

**Comment by teeohhem** [comment]
@ptnapoleon I actually ran into this recently too and it was because my java version was out of date. When I tried to start DSE manually, I got
"DSE 6.7 requires Java 8 update 151 or later. Java 8 update 65 is not supported."

However, through`ccm start`, the command eventually timed out with:
```
(my-ctool-env) [Fri Jan 24] 03:11 PM:~/source/studio[STUDIO-2914-doclinks*] ccm start
Traceback (most recent call last):
  File "/usr/local/bin/ccm", line 4, in <module>
    __import__('pkg_resources').run_script('ccm==3.1.2', 'ccm')
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Python/2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/ccm-3.1.2-py2.7.egg/EGG-INFO/scripts/ccm", line 105, in <module>

  File "build/bdist.macosx-10.12-intel/egg/ccmlib/cmds/cluster_cmds.py", line 490, in run
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/dse_cluster.py", line 75, in start
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/cluster.py", line 415, in start
  File "build/bdist.macosx-10.12-intel/egg/ccmlib/node.py", line 495, in watch_log_for
ccmlib.node.TimeoutError: 24 Jan 2020 20:14:38 [node1] Missing: ['Starting listening for CQL clients']:
.....
See system.log for remainder
```

However, there was nothing in my system.log. An upgraded java version fixed this ultimately. Hope this helps.
